# Generated by Django 4.2.3 on 2023-08-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='biography',
            field=models.CharField(default='opa', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='url_image',
            field=models.CharField(default='opa', max_length=500),
            preserve_default=False,
        ),
    ]
