# Generated by Django 4.2.3 on 2023-08-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_biography_account_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='biography',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='account',
            name='url_image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
