# Generated by Django 4.2.3 on 2023-09-07 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('url_img', models.CharField(max_length=2000)),
                ('normal_price', models.FloatField()),
                ('current_price', models.FloatField()),
            ],
        ),
    ]
