# Generated by Django 4.2.3 on 2023-09-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_created_at_game_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='url_img',
            new_name='url_image',
        ),
    ]
