# Generated by Django 4.2.3 on 2023-09-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(default='https://techcrunch.com/', max_length=2000),
            preserve_default=False,
        ),
    ]
