# Generated by Django 4.2.3 on 2023-09-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.CharField(default='https://techcrunch.com/wp-content/uploads/2021/09/AppleEvent.SEP14Keynote.Tim_Cook.01.jpg', max_length=2000),
            preserve_default=False,
        ),
    ]
